services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app # ソースコードのホットリロード用
      - ./models:/app/models:ro # ホストのモデルディレクトリを読み取り専用でマウント
      - ./backend/output:/app/output # 生成された音声ファイル
    env_file:
      - ./backend/.env # 環境変数ファイル
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # or 'all'
              capabilities: [gpu]
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true