version: '3.8'

services:
  voice-synthesis:
    build:
      context: . # voice_synthesis ディレクトリをコンテキストにする
      dockerfile: Dockerfile # 同じディレクトリにあるDockerfileを指定
    container_name: voice-synthesis-container
    volumes:
      - ./models:/app/models      # ホストのモデルフォルダをコンテナの/app/modelsにマウント
      - ./output:/app/output      # ホストの出力フォルダをコンテナの/app/outputにマウント
      # - ./src:/app/src          # (開発用オプション) ホストのsrcをマウントする場合はDockerfileのCOPYをコメントアウト
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # 利用するGPUの数を指定 (all でも可)
              capabilities: [gpu]
    # GPUを使うための環境変数 (docker-compose V2以降ではdeployセクションで十分な場合も多い)
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # env_file: # .env ファイルを使う場合はコメント解除
    #   - .env
    working_dir: /app
    tty: true           # コンテナ内でインタラクティブシェルを使うため
    stdin_open: true    # 同上 